card_payment:
  payment_type: "credit_card"
  installments:    
    - type: offline
      display_name: ""
      gateway: midtrans
      bank: bca
      channel: migs
      default: true
      active: true
      terms:
        - term: 0
          admin_fee:
            IDR:
              val_percentage: 2.9
              val_currency: 2000
              currency: "IDR"
        - term: 3
          installment_fee:
            IDR:
              val_percentage: 5.5
              val_currency: 2200
              currency: "IDR"  
        - term: 6
          installment_fee:
            IDR:
              val_percentage: 7.5
              val_currency: 2200
              currency: "IDR"
        - term: 12
          installment_fee:
            IDR:
              val_percentage: 9
              val_currency: 2200
              currency: "IDR"                                          
bank_transfers:
  - gateway: xendit
    payment_type: "bri_va"
    display_name: "BRI"
    admin_fee:
      IDR:
        val_percentage: 0
        val_currency: 4000
        currency: "IDR"
    waiting_time:
      duration: 1
      unit: day
  - gateway: midtrans
    payment_type: "bca_va"
    display_name: "BCA"
    admin_fee:
      IDR:
        val_percentage: 0
        val_currency: 4000
        currency: "IDR"
    waiting_time:
      duration: 1
      unit: day
  - gateway: midtrans
    payment_type: "mandiri_va"
    display_name: "Mandiri"
    admin_fee:
      IDR:
        val_percentage: 0
        val_currency: 2000
        currency: "IDR" 
    waiting_time:
      duration: 1
      unit: day        
  - gateway: midtrans
    payment_type: "bni_va"
    display_name: "BNI"
    admin_fee:
      IDR:
        val_percentage: 0
        val_currency: 2000
        currency: "IDR"
    waiting_time:
      duration: 1
      unit: day        
  - gateway: midtrans
    payment_type: "permata_va"
    display_name: "Bank Permata"
    admin_fee:
      IDR:
        val_percentage: 0
        val_currency: 2000
        currency: "IDR"
    waiting_time:
      duration: 1
      unit: day        
  - gateway: midtrans
    payment_type: "other_va"
    display_name: "Bank Lainnya"
    admin_fee:
      IDR:
        val_percentage: 0
        val_currency: 2000
        currency: "IDR"
    waiting_time:
      duration: 1
      unit: day                             
ewallets:
  - gateway: midtrans
    payment_type: "gopay"
    display_name: "Gopay"
    admin_fee:
      IDR:
        val_percentage: 0
        val_currency: 0
        currency: "IDR"
    waiting_time:
      duration: 15
      unit: minute     
  - gateway: xendit
    payment_type: "ovo"
    display_name: "OVO"
    admin_fee:
      IDR:
        val_percentage: 0
        val_currency: 0
        currency: "IDR"
    waiting_time:
      duration: 15
      unit: minute 
  - gateway: xendit
    payment_type: "dana"
    display_name: "DANA"
    admin_fee:
      IDR:
        val_percentage: 0
        val_currency: 0
        currency: "IDR"
    waiting_time:
      duration: 15
      unit: minute 
  - gateway: xendit
    payment_type: "linkaja"
    display_name: "LinkAja"
    admin_fee:
      IDR:
        val_percentage: 0
        val_currency: 0
        currency: "IDR"
    waiting_time:
      duration: 15
      unit: minute
  - gateway: midtrans
    payment_type: "shopeepay"
    display_name: "Shopee Pay"
    admin_fee:
      IDR:
        val_percentage: 0
        val_currency: 0
        currency: "IDR"
    waiting_time:
      duration: 15
      unit: minute
  - gateway: xendit
    payment_type: "qris"
    display_name: "QRIS"
    admin_fee:
      IDR:
        val_percentage: 0
        val_currency: 0
        currency: "IDR"
    waiting_time:
      duration: 15
      unit: minute
cstores:
  - gateway: midtrans
    payment_type: alfamart
    display_name: "Alfamart"
    admin_fee: 
      IDR:
        val_percentage: 0
        val_currency: 2000
        currency: "IDR"
    waiting_time:
      duration: 1
      unit: day        
cardless_credits:
  - gateway: midtrans
    payment_type: akulaku
    display_name: "Akulaku"
    admin_fee: 
      IDR:
        val_percentage: 2.0
        val_currency: 0
        currency: "IDR"
    waiting_time:
      duration: 1
      unit: day        
