# This file is gitignored. Never put the real credentials and commit it to git repo.
db:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: ""
  dbname: "ecom-payment"
payment:
  midtrans:
    secretKey: "midtrans-server-secret"
    clientKey: "midtrans-client-key"
    clientId: "midtrans-client-id"
  xendit:
    secretKey: ""
    callbackToken: ""
